# Generated by Django 4.2.4 on 2023-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refferal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('location', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
