# Generated by Django 4.2.6 on 2023-10-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refferals', '0003_refferal_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferal',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
