# Generated by Django 4.2.4 on 2023-08-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_contact_us_message_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_name',
            field=models.CharField(max_length=200),
        ),
    ]
