# Generated by Django 4.2.4 on 2023-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
