# Generated by Django 4.2.6 on 2023-10-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_location_client_refferal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrestedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('business_name', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('refferal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1500.0)),
                ('payment_code', models.CharField(blank=True, max_length=100, null=True)),
                ('pending', models.BooleanField(default=True)),
                ('paid', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.intrestedclient')),
            ],
        ),
    ]
