# Generated by Django 4.2.6 on 2023-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_intrestedclient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
