# Generated by Django 4.2.4 on 2023-10-05 06:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_about_us_image_company_hero_image_customer_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
