# Generated by Django 4.2.4 on 2023-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_about_us_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='description',
            field=models.TextField(),
        ),
    ]
