# Generated by Django 4.2.6 on 2023-11-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_about_us_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pitch',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='company',
            name='tagline',
            field=models.TextField(max_length=150),
        ),
    ]
